obstacle_range: 4.0
raytrace_range: 5.0
inflation_radius: 0.75

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: aero/laser_link, data_type: LaserScan, topic: /aero/laser, marking: true, clearing: true}

global_frame: aero/odom
robot_base_frame: aero/base_link
transform_tolerance: 0.6